### ISSUE TITLE
Support nested structures

### ISSUE THREAD

**Issue by Kangaroux** [Kangaroux/go-map-schema#1]
If `dst` contains a struct which is not embedded, we should recursively compare it. `FieldMismatch` will need to be updated to include something that describes the field's "path". Having a list of strings that keeps track of the parent would probably be the easiest approach.

**Comment by etloreq** [comment]
Do you want to have the FieldMismatch.Field contain the entire path or just the field name? 
"Missing fields" must also work for nested structs in the same way, but these are strings, not structs.  So if you don't want to make breaking changes, I think it can't be changed to structs with a path -> the path for missing fields can only be written in the missing field value.
So the only option I can see now **without changing the type of missing fields** is to print the path in the FieldMismatch.Field and in the "missing field" itself.

But I think it would be better to have both mismatched and missing fields as structs with a path.

**Comment by Kangaroux** [comment]
@Quanare I agree, that's a good point. Maybe have a struct to represent a field path, and a `String()` method that returns the path with dots e.g. `foo.bar.baz`. 

Not worried about breaking changes, this is still pre-v1
